### ISSUE TITLE
demo app has a CORS issue

### ISSUE THREAD

**Issue by SbiCA** [ravendb/samples-crypto-app#1]
Access to fetch at 'https://ravendb-stock-demo-backend.azurewebsites.net/api/MarketSymbol/BTC-USDT?' from origin 'https://ravendb-samples-crypto-app.netlify.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I guess you need to enable CORS on the app service 

because if I'm calling the backend directly it works https://ravendb-stock-demo-backend.azurewebsites.net/api/MarketSymbol/BTC-USDT

**Comment by ayende** [comment]
Thanks, we'll look into that.

**Comment by kamranayub** [comment]
Thanks, fixed! I had updated the URL but missed the CORS policy.
